# Generated by Django 3.2.7 on 2021-10-19 18:11

import uuid

import django.contrib.postgres.fields
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, error_messages={'unique': 'Пользователь с таким именем уже существует'}, help_text='Обязательное. Не более 150 символов.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Введите имя пользователя. Может содержать только буквы, цифры и символы @/./+/-/_', 'invalid')], verbose_name='Имя пользователя')),
                ('first_name', models.CharField(blank=True, max_length=250, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=250, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=250, verbose_name='Email')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('permissions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, default=list, size=8)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': '"content"."users"',
                'index_together': {('first_name', 'last_name', 'username')},
            },
        ),
    ]
