# Generated by Django 3.2.7 on 2021-09-16 20:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(blank=True, max_length=250, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(db_index=True, error_messages={'unique': 'Пользователь с таким именем уже существует'}, help_text='Обязательное. Не более 150 символов.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Введите имя пользователя. Может содержать только буквы, цифры и символы @/./+/-/_', 'invalid')], verbose_name='Имя пользователя'),
        ),
    ]
