# Generated by Django 3.2 on 2021-09-05 19:17

import uuid

import django.core.validators
from django.db import migrations, models

import movies.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'genre',
                'verbose_name_plural': 'genres',
                'db_table': 'content.genre',
            },
            bases=(movies.models.TimeStampedMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Filmwork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('rating', models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='rating')),
                ('file_path', models.FileField(blank=True, upload_to='film_works/', verbose_name='file')),
                ('age_censor', models.IntegerField(verbose_name='censor')),
                ('genre', models.ManyToManyField(to='movies.Genre')),
                ('person', models.ManyToManyField(to='persons.Person')),
            ],
            options={
                'verbose_name': 'filmwork',
                'verbose_name_plural': 'filmworks',
                'db_table': 'content.film_work',
            },
            bases=(models.Model, movies.models.TimeStampedMixin),
        ),
    ]
