# Generated by Django 3.2.7 on 2021-10-16 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='film_works/', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='filmwork',
            name='imdb_rating',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='imdb_rating'),
        ),
        migrations.AlterField(
            model_name='filmwork',
            name='ratings',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='rating'),
        ),
    ]
