# Generated by Django 3.2.8 on 2021-10-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='filmworkgenres',
            constraint=models.UniqueConstraint(fields=('film_work', 'genre'), name='film_work_genre'),
        ),
        migrations.AddConstraint(
            model_name='filmworkpersonstype',
            constraint=models.UniqueConstraint(fields=('film_work', 'person'), name='film_work_person'),
        ),
    ]
