# Generated by Django 3.2.7 on 2021-09-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='title'),
        ),
    ]
