# Generated by Django 3.2.7 on 2021-10-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20211016_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='age_censor',
            field=models.IntegerField(blank=True, null=True, verbose_name='censor'),
        ),
    ]
