# Generated by Django 3.2.7 on 2021-10-16 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_filmwork_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmworkgenres',
            old_name='film_work_id',
            new_name='film_work',
        ),
        migrations.RenameField(
            model_name='filmworkgenres',
            old_name='genre_id',
            new_name='genre',
        ),
    ]
