# Generated by Django 3.2.7 on 2021-10-16 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0007_auto_20211016_1252'),
        ('movies', '0006_auto_20211016_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmworkPersonsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_person', models.CharField(blank=True, choices=[('actors', 'Actors'), ('directions', 'Director'), ('writers', 'Writer')], max_length=11, verbose_name='Профессия')),
                ('film_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.filmwork')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.person')),
            ],
            options={
                'db_table': '"content"."film_work_persons_type"',
            },
        ),
        migrations.AddField(
            model_name='filmwork',
            name='person',
            field=models.ManyToManyField(through='movies.FilmworkPersonsType', to='persons.Person'),
        ),
    ]
