# Generated by Django 3.2.7 on 2021-10-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0007_auto_20211016_1252'),
        ('movies', '0007_auto_20211016_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='genre',
            field=models.ManyToManyField(related_name='genres', through='movies.FilmworkGenres', to='movies.Genre'),
        ),
        migrations.AlterField(
            model_name='filmwork',
            name='person',
            field=models.ManyToManyField(related_name='persons', through='movies.FilmworkPersonsType', to='persons.Person'),
        ),
    ]
