# Generated by Django 3.2.7 on 2021-10-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0007_auto_20211016_1252'),
        ('movies', '0009_auto_20211016_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='genre', through='movies.FilmworkGenres', to='movies.Genre'),
        ),
        migrations.AlterField(
            model_name='filmwork',
            name='person',
            field=models.ManyToManyField(blank=True, related_name='person', through='movies.FilmworkPersonsType', to='persons.Person'),
        ),
    ]
