# Generated by Django 3.2.7 on 2021-10-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20211016_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='filmwork',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
