# Generated by Django 3.2.7 on 2021-10-16 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_alter_filmworkpersonstype_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmworkpersonstype',
            name='film_work',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movies.filmwork'),
        ),
    ]
