# Generated by Django 3.2.7 on 2021-09-17 17:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_alter_serieswork_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='serieswork',
            name='created_at',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='created_at'),
        ),
    ]
