# Generated by Django 3.2.7 on 2021-10-16 09:52

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=250, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=250, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=250, verbose_name='Отчество')),
                ('birthdate', models.DateField(verbose_name='День рождения')),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'persons',
                'db_table': '"content"."person"',
                'index_together': {('first_name', 'last_name', 'patronymic')},
            },
        ),
        migrations.CreateModel(
            name='FilmworkPersonsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('actors', 'Actors'), ('director', 'Director'), ('writers', 'Writer')], max_length=8, verbose_name='Профессия')),
                ('film_work_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.filmwork')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.person')),
            ],
            options={
                'db_table': '"content"."film_work_persons_type"',
            },
        ),
    ]
