# Generated by Django 3.2.7 on 2021-10-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='film',
            field=models.ManyToManyField(through='persons.FilmworkPersonsType', to='movies.Filmwork'),
        ),
    ]
