# Generated by Django 3.2.7 on 2021-09-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=250, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='person',
            name='profession_type',
            field=models.CharField(blank=True, choices=[(1, 'Актер'), (2, 'Режиссер'), (3, 'Сценарист')], max_length=10, verbose_name='Профессия'),
        ),
    ]
