# Generated by Django 3.2.7 on 2021-10-16 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_alter_person_patronymic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmworkpersonstype',
            old_name='film_work_id',
            new_name='film_work',
        ),
        migrations.RenameField(
            model_name='filmworkpersonstype',
            old_name='person_id',
            new_name='person',
        ),
    ]
