# Generated by Django 3.2.7 on 2021-10-16 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_auto_20211016_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmworkpersonstype',
            old_name='type',
            new_name='type_person',
        ),
    ]
