# Generated by Django 3.2.7 on 2021-10-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0005_rename_type_filmworkpersonstype_type_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmworkpersonstype',
            name='type_person',
            field=models.CharField(blank=True, choices=[('actors', 'Actors'), ('directions', 'Director'), ('writers', 'Writer')], max_length=11, verbose_name='Профессия'),
        ),
    ]
