# Generated by Django 3.2.7 on 2021-10-16 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0006_alter_filmworkpersonstype_type_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='film',
        ),
        migrations.DeleteModel(
            name='FilmworkPersonsType',
        ),
    ]
